module.exports ={
   ADD_POSTS : "ADD_POSTS",
   ADD_POST : "ADD_POST",
   REMOVE_POSTS: "REMOVE_POSTS",
   LOAD_PROFILE: "LOAD_PROFILE",
   UPDATE_FRIENDS: "UPDATE_FRIENDS",
   SOCKET_PROFILE: "SOCKET_PROFILE",
   ADD_NEW_NOTIFICAION: "ADD_NEW_NOTIFICAION",
   OPEN_NOTIFY: "OPEN_NOTIFY",
   ADD_COMMENTS: "ADD_COMMENTS",
   ADD_COMMENT: "ADD_COMMENT",
}